import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";

interface Manifest {
  migrations: Array<{ file: string; checksum: string }>;
}

const packageRoot = process.cwd();
const sqlRoot = join(packageRoot, "sql");
const manifest = JSON.parse(readFileSync(join(sqlRoot, "manifest.json"), "utf8")) as Manifest;

test("manifest checksums match every source migration", () => {
  for (const entry of manifest.migrations) {
    const content = readFileSync(join(sqlRoot, entry.file), "utf8");
    const actual = createHash("sha256").update(content).digest("hex");
    assert.equal(actual, entry.checksum, entry.file);
  }
});

test("install artifact contains every migration exactly once and no consumer CLI metadata", () => {
  const install = readFileSync(join(sqlRoot, "install.sql"), "utf8");
  for (const entry of manifest.migrations) {
    const filename = entry.file.replace("migrations/", "");
    assert.equal(install.split(`-- BEGIN ${filename}`).length - 1, 1, filename);
  }
  assert.doesNotMatch(install, /Generated by supabase-tenant-rbac (?:init|upgrade)/);
});

test("privileged SQL has no dynamic row dispatcher or public role mutation command", () => {
  const install = readFileSync(join(sqlRoot, "install.sql"), "utf8");
  assert.doesNotMatch(install, /create\s+or\s+replace\s+function\s+multitenancy\.authorize_row/i);
  assert.doesNotMatch(install, /when\s+'role\.(?:create|update|delete|set_permissions)'/i);
  assert.match(install, /roles and role permissions are DBA-managed/);
  assert.match(install, /revoke all on table multitenancy\.roles, multitenancy\.role_permissions/);
});
